### ISSUE TITLE
cpuid.CPU.AVX512F undefined (type cpuid.CPUInfo has no field or method AVX512F)

### ISSUE THREAD

**Issue by Racle** [minio/md5-simd#19]
I'm trying to run minio-go on virtual machine (and in Docker environment).

When I try to build or go get, i'll get this error message:

``` 
../../../go/src/github.com/minio/md5-simd/block_amd64.go:86:23: cpuid.CPU.AVX512F undefined (type cpuid.CPUInfo has no field or method AVX512F)
../../../go/src/github.com/minio/md5-simd/md5-server_amd64.go:63:15: cpuid.CPU.AVX2 undefined (type cpuid.CPUInfo has no field or method AVX2)
``` 

I attached quick example project.
[minio-example.zip](https://github.com/minio/md5-simd/files/5660044/minio-example.zip)

Run `make run` or manually `docker build -t minio-example .` and you should see the same error

**Comment by harshavardhana** [comment]
Just set GO111MODULE=on - we haven't yet upgraded to latest cpuid package yet.
