### ISSUE TITLE
md5Server does not properly clean up its clients

### ISSUE THREAD

**Issue by koen-struyve-q** [minio/md5-simd#27]
In the 'client disconnected' case on this line:

https://github.com/minio/md5-simd/blob/30ad8af83f6868c2a30c615f3edf1a9366bf3f89/md5-server_amd64.go#L136

the delete is carried out using ```block.uid```. However in this case this will always be zero, causing improper cleanup of the clients, and performance degradation over time. The correct variable to use here is ```uid```.

**Comment by klauspost** [comment]
Thanks for the report. PR #28 applies the fix.
