### ISSUE TITLE
avx512: use VPTERNLOGQ for ternary operations

### ISSUE THREAD

**Issue by klauspost** [minio/md5-simd#3]
http://www.0x80.pl/articles/avx512-ternary-functions.html

Made this calculator: https://play.golang.org/p/JkeaBPpu2b-

ROUND1:

```
	VXORPS  c, tmp, tmp            \
[...]
	VANDPS  b, tmp, tmp            \
	VXORPS  d, tmp, tmp            \

```
This looks to be `tmp = (((c ^ tmp) & b) ^ d)`. This should be able to be reduced by 1 instruction.

If to replace the last two `tmp = ((tmp & b) ^ d)`.  `c=tmp, b=b, a=d)`, meaning `c = ((c & b) ^ a)`

-> `VPTERNLOG $120, d, b, tmp` - https://play.golang.org/p/4A9Ex1-q9ft

ROUND3:
```
	VXORPS  d, tmp, tmp            \
	VXORPS  b, tmp, tmp            \
```

Easy, `VPTERNLOG $150, b, d, tmp` - https://play.golang.org/p/hNUMvRjSwQN

ROUND4:

```
	VORPS  b, tmp, tmp            \
	VXORPS c, tmp, tmp            \
```

This looks like `tmp = (b | tmp) ^c`. With params, `c = (b | c) ^a`, so 

-> `VPTERNLOG $30, c, b, tmp` - https://play.golang.org/p/2NqJElhLfSH

**Comment by fwessels** [comment]
Thanks for the suggestion, fixed via befe68c
