### ISSUE TITLE
Quickly slows down

### ISSUE THREAD

**Issue by vitalif** [minio/md5-simd#33]
Hi
We attempted to use your library in our server and discovered that md5 calculation quickly slows down
I then tried to reproduce the slowdown and I was able to do that using the following example:
```
package main

import (
    "fmt"
    "time"
    "math/rand"
    "github.com/minio/md5-simd"
)

func main() {
    md5Server := md5simd.NewServer()
    n := 200
    sem := make(chan int)
    for i := 0; i < n; i++ {
        go func() {
            buf := make([]byte, 1048569)
            for i := 0; i < len(buf); i++ {
                buf[i] = byte(i * 53)
            }
            for i := 0; i < 1000; i++ {
                time.Sleep(time.Duration(1500 * rand.Float32()) * time.Millisecond)
                start := time.Now()
                c := md5Server.NewHash()
                for j := 0; j < 15; j++ {
                    c.Write(buf)
                }
                c.Sum(nil)
                c.Close()
                dur := time.Now().Sub(start)
                fmt.Printf("%.02f s\n", dur.Seconds())
            }
            sem <- 1
        }()
    }
    for i := 0; i < n; i++ {
        <- sem
    }
}
```

It's not exactly our case because we actually use sync.Pool over md5Server.NewHash() so we don't Close() the hasher but rather Reset() it after each usage and put back to the pool, and I couldn't reproduce the slowdown easily using the pool.

But anyway I'm reporting the bug to you, maybe you'll have an idea about why that happens.

I also looked at the synchronisation/channel code and I thought that maybe it would be better to use reflect.Select https://golang.org/pkg/reflect/#Select over all client channels instead of nontrivial synchronisation based on N+1 channels... But I'm of course not sure that the slowdown is caused by this thing.

**Comment by vitalif** [comment]
Yeah, of course, in the first seconds it slows down from ~0.2 sec to ~1 sec, it's OK, it's just caused by random delays. But in my case then it continues to slow down and reaches 2 sec, 3 sec, 4 sec and so on. Which isn't caused by delays.

Here's the second implementation with a pool:

```
package main

import (
    "fmt"
    "time"
    "hash"
    "math/rand"
    "github.com/minio/md5-simd"
    "sync"
)

func main() {
    md5Server := md5simd.NewServer()
    p := sync.Pool{
        New: func() interface{} {
            return md5Server.NewHash()
        },
    }
    n := 200
    sem := make(chan int)
    for i := 0; i < n; i++ {
        go func() {
            buf := make([]byte, 1048569)
            for i := 0; i < len(buf); i++ {
                buf[i] = byte(i * 53)
            }
            for i := 0; i < 1000; i++ {
                time.Sleep(time.Duration(1500 * rand.Float32()) * time.Millisecond)
                start := time.Now()
                c := p.Get().(hash.Hash)
                for j := 0; j < 15; j++ {
                    c.Write(buf)
                }
                c.Sum(nil)
                c.Reset()
                p.Put(c)
                dur := time.Now().Sub(start)
                fmt.Printf("%.02f s\n", dur.Seconds())
            }
            sem <- 1
        }()
    }
    for i := 0; i < n; i++ {
        <- sem
    }
}
```

This one doesn't slow down for me - i.e. it also slows down in the beginning from ~0.2sec to ~1sec and then oscillates between 0.8sec-1.2sec, but does not slow down anymore.

Interestingly my colleague says that on his PC the result is the opposite: reset()-based implementation slows down and close()-based doesn't :D

**Comment by vitalif** [comment]
PS About the concurrent hashes - I understand the principle and in fact I think it would be good to implement an internal "2D pool" in the library itself so it can use all cores instead of just 1 :-)

**Comment by klauspost** [comment]
Yes, it stabilizes around 0.5s->0.7s for me, so I had to assume you meant the initial fast completions.

You cannot leak hashers, you *must* call Close to de-register it. If you stuff them in a sync.Pool you are leaking them.

To reuse them add a 16 sized `chan hash.Hash`. Create 16 clients and put them on the channel.

I can't see anything actionable here.

**Comment by vitalif** [comment]
I don't leak them, am I doing anything wrong in the first example?
It doesn't stabilize for me.

**Comment by vitalif** [comment]
It reaches 2 then 3 then 4 sec and so on

**Comment by vitalif** [comment]
The example with sync.Pool doesn't slow down for me, so my question is why does the first example slow down?))

**Comment by klauspost** [comment]
First example doesn't slow down for me. Here is about 5 minutes: [out.txt.gz](https://github.com/minio/md5-simd/files/9812874/out.txt.gz)

Is your system overheating?

**Comment by vitalif** [comment]
No idea... doesn't seem so. Problem is that it reproduces in pre-production environment too (but with a pool) :) but maybe that's also because of that leak via the pool.

**Comment by klauspost** [comment]
Made this which shows more fine grained throughput:

```
func TestSomething(t *testing.T) {
	var total int64

	md5Server := NewServer()
	n := 2000
	go func() {
		t := time.NewTicker(1 * time.Second)
		lastTime := time.Now()
		for range t.C {
			elapsed := time.Since(lastTime)
			processed := atomic.SwapInt64(&total, 0)
			lastTime = time.Now()
			fmt.Printf("%0.2fGB/s\n", float64(processed)/elapsed.Seconds()/float64(1<<30))
		}
	}()

	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			buf := make([]byte, 1048569)
			for i := 0; i < len(buf); i++ {
				buf[i] = byte(i * 53)
			}
			for i := 0; i < 1000; i++ {
				time.Sleep(time.Duration(1500*rand.Float32()) * time.Millisecond)
				c := md5Server.NewHash()
				for j := 0; j < 15; j++ {
					c.Write(buf)
					atomic.AddInt64(&total, int64(len(buf)))
				}
				c.Sum(nil)
				c.Close()
			}
		}()
	}
	wg.Wait()
}
```

Again; not seeing anything out of the ordinary.

You are welcome to try to rewrite the synchronization. You can also use `BenchmarkAvx512` for less competitive tests to make sure those don't regress.
